// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: iam/iam.proto

package iam

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AuthReq) Validate() error {
	if this.Auth == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Auth", fmt.Errorf(`value '%v' must not be an empty string`, this.Auth))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}
func (this *AuthResp) Validate() error {
	return nil
}
func (this *RefreshReq) Validate() error {
	if !(len(this.Token) == 20) {
		return github_com_mwitkow_go_proto_validators.FieldError("Token", fmt.Errorf(`value '%v' must have a length equal to '20'`, this.Token))
	}
	return nil
}
func (this *RefreshResp) Validate() error {
	return nil
}
