// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResonateUserListUsersParams creates a new ResonateUserListUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserListUsersParams() *ResonateUserListUsersParams {
	return &ResonateUserListUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserListUsersParamsWithTimeout creates a new ResonateUserListUsersParams object
// with the ability to set a timeout on a request.
func NewResonateUserListUsersParamsWithTimeout(timeout time.Duration) *ResonateUserListUsersParams {
	return &ResonateUserListUsersParams{
		timeout: timeout,
	}
}

// NewResonateUserListUsersParamsWithContext creates a new ResonateUserListUsersParams object
// with the ability to set a context for a request.
func NewResonateUserListUsersParamsWithContext(ctx context.Context) *ResonateUserListUsersParams {
	return &ResonateUserListUsersParams{
		Context: ctx,
	}
}

// NewResonateUserListUsersParamsWithHTTPClient creates a new ResonateUserListUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserListUsersParamsWithHTTPClient(client *http.Client) *ResonateUserListUsersParams {
	return &ResonateUserListUsersParams{
		HTTPClient: client,
	}
}

/* ResonateUserListUsersParams contains all the parameters to send to the API endpoint
   for the resonate user list users operation.

   Typically these are written to a http.Request.
*/
type ResonateUserListUsersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user list users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserListUsersParams) WithDefaults() *ResonateUserListUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user list users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserListUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user list users params
func (o *ResonateUserListUsersParams) WithTimeout(timeout time.Duration) *ResonateUserListUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user list users params
func (o *ResonateUserListUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user list users params
func (o *ResonateUserListUsersParams) WithContext(ctx context.Context) *ResonateUserListUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user list users params
func (o *ResonateUserListUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user list users params
func (o *ResonateUserListUsersParams) WithHTTPClient(client *http.Client) *ResonateUserListUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user list users params
func (o *ResonateUserListUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserListUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
