// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// NewResonateUserUpdateUserRestrictedParams creates a new ResonateUserUpdateUserRestrictedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserUpdateUserRestrictedParams() *ResonateUserUpdateUserRestrictedParams {
	return &ResonateUserUpdateUserRestrictedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserUpdateUserRestrictedParamsWithTimeout creates a new ResonateUserUpdateUserRestrictedParams object
// with the ability to set a timeout on a request.
func NewResonateUserUpdateUserRestrictedParamsWithTimeout(timeout time.Duration) *ResonateUserUpdateUserRestrictedParams {
	return &ResonateUserUpdateUserRestrictedParams{
		timeout: timeout,
	}
}

// NewResonateUserUpdateUserRestrictedParamsWithContext creates a new ResonateUserUpdateUserRestrictedParams object
// with the ability to set a context for a request.
func NewResonateUserUpdateUserRestrictedParamsWithContext(ctx context.Context) *ResonateUserUpdateUserRestrictedParams {
	return &ResonateUserUpdateUserRestrictedParams{
		Context: ctx,
	}
}

// NewResonateUserUpdateUserRestrictedParamsWithHTTPClient creates a new ResonateUserUpdateUserRestrictedParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserUpdateUserRestrictedParamsWithHTTPClient(client *http.Client) *ResonateUserUpdateUserRestrictedParams {
	return &ResonateUserUpdateUserRestrictedParams{
		HTTPClient: client,
	}
}

/* ResonateUserUpdateUserRestrictedParams contains all the parameters to send to the API endpoint
   for the resonate user update user restricted operation.

   Typically these are written to a http.Request.
*/
type ResonateUserUpdateUserRestrictedParams struct {

	// Body.
	Body *models.UserUserUpdateRestrictedRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user update user restricted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserUpdateUserRestrictedParams) WithDefaults() *ResonateUserUpdateUserRestrictedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user update user restricted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserUpdateUserRestrictedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) WithTimeout(timeout time.Duration) *ResonateUserUpdateUserRestrictedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) WithContext(ctx context.Context) *ResonateUserUpdateUserRestrictedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) WithHTTPClient(client *http.Client) *ResonateUserUpdateUserRestrictedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) WithBody(body *models.UserUserUpdateRestrictedRequest) *ResonateUserUpdateUserRestrictedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) SetBody(body *models.UserUserUpdateRestrictedRequest) {
	o.Body = body
}

// WithID adds the id to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) WithID(id string) *ResonateUserUpdateUserRestrictedParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user update user restricted params
func (o *ResonateUserUpdateUserRestrictedParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserUpdateUserRestrictedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
