// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// NewResonateUserAddUserParams creates a new ResonateUserAddUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserAddUserParams() *ResonateUserAddUserParams {
	return &ResonateUserAddUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserAddUserParamsWithTimeout creates a new ResonateUserAddUserParams object
// with the ability to set a timeout on a request.
func NewResonateUserAddUserParamsWithTimeout(timeout time.Duration) *ResonateUserAddUserParams {
	return &ResonateUserAddUserParams{
		timeout: timeout,
	}
}

// NewResonateUserAddUserParamsWithContext creates a new ResonateUserAddUserParams object
// with the ability to set a context for a request.
func NewResonateUserAddUserParamsWithContext(ctx context.Context) *ResonateUserAddUserParams {
	return &ResonateUserAddUserParams{
		Context: ctx,
	}
}

// NewResonateUserAddUserParamsWithHTTPClient creates a new ResonateUserAddUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserAddUserParamsWithHTTPClient(client *http.Client) *ResonateUserAddUserParams {
	return &ResonateUserAddUserParams{
		HTTPClient: client,
	}
}

/* ResonateUserAddUserParams contains all the parameters to send to the API endpoint
   for the resonate user add user operation.

   Typically these are written to a http.Request.
*/
type ResonateUserAddUserParams struct {

	// Body.
	Body *models.UserUserAddRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user add user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserAddUserParams) WithDefaults() *ResonateUserAddUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user add user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserAddUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user add user params
func (o *ResonateUserAddUserParams) WithTimeout(timeout time.Duration) *ResonateUserAddUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user add user params
func (o *ResonateUserAddUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user add user params
func (o *ResonateUserAddUserParams) WithContext(ctx context.Context) *ResonateUserAddUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user add user params
func (o *ResonateUserAddUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user add user params
func (o *ResonateUserAddUserParams) WithHTTPClient(client *http.Client) *ResonateUserAddUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user add user params
func (o *ResonateUserAddUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the resonate user add user params
func (o *ResonateUserAddUserParams) WithBody(body *models.UserUserAddRequest) *ResonateUserAddUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the resonate user add user params
func (o *ResonateUserAddUserParams) SetBody(body *models.UserUserAddRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserAddUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
