// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserUpdateUserReader is a Reader for the ResonateUserUpdateUser structure.
type ResonateUserUpdateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserUpdateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserUpdateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserUpdateUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserUpdateUserOK creates a ResonateUserUpdateUserOK with default headers values
func NewResonateUserUpdateUserOK() *ResonateUserUpdateUserOK {
	return &ResonateUserUpdateUserOK{}
}

/* ResonateUserUpdateUserOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserUpdateUserOK struct {
	Payload models.UserEmpty
}

func (o *ResonateUserUpdateUserOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/user/{id}][%d] resonateUserUpdateUserOK  %+v", 200, o.Payload)
}
func (o *ResonateUserUpdateUserOK) GetPayload() models.UserEmpty {
	return o.Payload
}

func (o *ResonateUserUpdateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserUpdateUserDefault creates a ResonateUserUpdateUserDefault with default headers values
func NewResonateUserUpdateUserDefault(code int) *ResonateUserUpdateUserDefault {
	return &ResonateUserUpdateUserDefault{
		_statusCode: code,
	}
}

/* ResonateUserUpdateUserDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserUpdateUserDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user update user default response
func (o *ResonateUserUpdateUserDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserUpdateUserDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/user/{id}][%d] ResonateUser_UpdateUser default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserUpdateUserDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserUpdateUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
