// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserDeleteUserReader is a Reader for the ResonateUserDeleteUser structure.
type ResonateUserDeleteUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserDeleteUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserDeleteUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserDeleteUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserDeleteUserOK creates a ResonateUserDeleteUserOK with default headers values
func NewResonateUserDeleteUserOK() *ResonateUserDeleteUserOK {
	return &ResonateUserDeleteUserOK{}
}

/* ResonateUserDeleteUserOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserDeleteUserOK struct {
	Payload models.UserEmpty
}

func (o *ResonateUserDeleteUserOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/restricted/user/{id}][%d] resonateUserDeleteUserOK  %+v", 200, o.Payload)
}
func (o *ResonateUserDeleteUserOK) GetPayload() models.UserEmpty {
	return o.Payload
}

func (o *ResonateUserDeleteUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserDeleteUserDefault creates a ResonateUserDeleteUserDefault with default headers values
func NewResonateUserDeleteUserDefault(code int) *ResonateUserDeleteUserDefault {
	return &ResonateUserDeleteUserDefault{
		_statusCode: code,
	}
}

/* ResonateUserDeleteUserDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserDeleteUserDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user delete user default response
func (o *ResonateUserDeleteUserDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserDeleteUserDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/restricted/user/{id}][%d] ResonateUser_DeleteUser default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserDeleteUserDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserDeleteUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
