// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserUpdateUserRestrictedReader is a Reader for the ResonateUserUpdateUserRestricted structure.
type ResonateUserUpdateUserRestrictedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserUpdateUserRestrictedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserUpdateUserRestrictedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserUpdateUserRestrictedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserUpdateUserRestrictedOK creates a ResonateUserUpdateUserRestrictedOK with default headers values
func NewResonateUserUpdateUserRestrictedOK() *ResonateUserUpdateUserRestrictedOK {
	return &ResonateUserUpdateUserRestrictedOK{}
}

/* ResonateUserUpdateUserRestrictedOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserUpdateUserRestrictedOK struct {
	Payload models.UserEmpty
}

func (o *ResonateUserUpdateUserRestrictedOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/restricted/user/{id}][%d] resonateUserUpdateUserRestrictedOK  %+v", 200, o.Payload)
}
func (o *ResonateUserUpdateUserRestrictedOK) GetPayload() models.UserEmpty {
	return o.Payload
}

func (o *ResonateUserUpdateUserRestrictedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserUpdateUserRestrictedDefault creates a ResonateUserUpdateUserRestrictedDefault with default headers values
func NewResonateUserUpdateUserRestrictedDefault(code int) *ResonateUserUpdateUserRestrictedDefault {
	return &ResonateUserUpdateUserRestrictedDefault{
		_statusCode: code,
	}
}

/* ResonateUserUpdateUserRestrictedDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserUpdateUserRestrictedDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user update user restricted default response
func (o *ResonateUserUpdateUserRestrictedDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserUpdateUserRestrictedDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/restricted/user/{id}][%d] ResonateUser_UpdateUserRestricted default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserUpdateUserRestrictedDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserUpdateUserRestrictedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
