// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResonateUserGetUserCreditsParams creates a new ResonateUserGetUserCreditsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserGetUserCreditsParams() *ResonateUserGetUserCreditsParams {
	return &ResonateUserGetUserCreditsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserGetUserCreditsParamsWithTimeout creates a new ResonateUserGetUserCreditsParams object
// with the ability to set a timeout on a request.
func NewResonateUserGetUserCreditsParamsWithTimeout(timeout time.Duration) *ResonateUserGetUserCreditsParams {
	return &ResonateUserGetUserCreditsParams{
		timeout: timeout,
	}
}

// NewResonateUserGetUserCreditsParamsWithContext creates a new ResonateUserGetUserCreditsParams object
// with the ability to set a context for a request.
func NewResonateUserGetUserCreditsParamsWithContext(ctx context.Context) *ResonateUserGetUserCreditsParams {
	return &ResonateUserGetUserCreditsParams{
		Context: ctx,
	}
}

// NewResonateUserGetUserCreditsParamsWithHTTPClient creates a new ResonateUserGetUserCreditsParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserGetUserCreditsParamsWithHTTPClient(client *http.Client) *ResonateUserGetUserCreditsParams {
	return &ResonateUserGetUserCreditsParams{
		HTTPClient: client,
	}
}

/* ResonateUserGetUserCreditsParams contains all the parameters to send to the API endpoint
   for the resonate user get user credits operation.

   Typically these are written to a http.Request.
*/
type ResonateUserGetUserCreditsParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user get user credits params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserGetUserCreditsParams) WithDefaults() *ResonateUserGetUserCreditsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user get user credits params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserGetUserCreditsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) WithTimeout(timeout time.Duration) *ResonateUserGetUserCreditsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) WithContext(ctx context.Context) *ResonateUserGetUserCreditsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) WithHTTPClient(client *http.Client) *ResonateUserGetUserCreditsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) WithID(id string) *ResonateUserGetUserCreditsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user get user credits params
func (o *ResonateUserGetUserCreditsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserGetUserCreditsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
