// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserGetUserRestrictedReader is a Reader for the ResonateUserGetUserRestricted structure.
type ResonateUserGetUserRestrictedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserGetUserRestrictedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserGetUserRestrictedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserGetUserRestrictedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserGetUserRestrictedOK creates a ResonateUserGetUserRestrictedOK with default headers values
func NewResonateUserGetUserRestrictedOK() *ResonateUserGetUserRestrictedOK {
	return &ResonateUserGetUserRestrictedOK{}
}

/* ResonateUserGetUserRestrictedOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserGetUserRestrictedOK struct {
	Payload *models.UserUserPrivateResponse
}

func (o *ResonateUserGetUserRestrictedOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/restricted/user/{id}][%d] resonateUserGetUserRestrictedOK  %+v", 200, o.Payload)
}
func (o *ResonateUserGetUserRestrictedOK) GetPayload() *models.UserUserPrivateResponse {
	return o.Payload
}

func (o *ResonateUserGetUserRestrictedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserUserPrivateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserGetUserRestrictedDefault creates a ResonateUserGetUserRestrictedDefault with default headers values
func NewResonateUserGetUserRestrictedDefault(code int) *ResonateUserGetUserRestrictedDefault {
	return &ResonateUserGetUserRestrictedDefault{
		_statusCode: code,
	}
}

/* ResonateUserGetUserRestrictedDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserGetUserRestrictedDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user get user restricted default response
func (o *ResonateUserGetUserRestrictedDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserGetUserRestrictedDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/restricted/user/{id}][%d] ResonateUser_GetUserRestricted default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserGetUserRestrictedDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserGetUserRestrictedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
