// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserListUsersUserGroupsReader is a Reader for the ResonateUserListUsersUserGroups structure.
type ResonateUserListUsersUserGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserListUsersUserGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserListUsersUserGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserListUsersUserGroupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserListUsersUserGroupsOK creates a ResonateUserListUsersUserGroupsOK with default headers values
func NewResonateUserListUsersUserGroupsOK() *ResonateUserListUsersUserGroupsOK {
	return &ResonateUserListUsersUserGroupsOK{}
}

/* ResonateUserListUsersUserGroupsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserListUsersUserGroupsOK struct {
	Payload *models.UserUserGroupListResponse
}

func (o *ResonateUserListUsersUserGroupsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/users/{id}/usergroups][%d] resonateUserListUsersUserGroupsOK  %+v", 200, o.Payload)
}
func (o *ResonateUserListUsersUserGroupsOK) GetPayload() *models.UserUserGroupListResponse {
	return o.Payload
}

func (o *ResonateUserListUsersUserGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserUserGroupListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserListUsersUserGroupsDefault creates a ResonateUserListUsersUserGroupsDefault with default headers values
func NewResonateUserListUsersUserGroupsDefault(code int) *ResonateUserListUsersUserGroupsDefault {
	return &ResonateUserListUsersUserGroupsDefault{
		_statusCode: code,
	}
}

/* ResonateUserListUsersUserGroupsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserListUsersUserGroupsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user list users user groups default response
func (o *ResonateUserListUsersUserGroupsDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserListUsersUserGroupsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/users/{id}/usergroups][%d] ResonateUser_ListUsersUserGroups default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserListUsersUserGroupsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserListUsersUserGroupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
