// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserGetUserGroupReader is a Reader for the ResonateUserGetUserGroup structure.
type ResonateUserGetUserGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserGetUserGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserGetUserGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserGetUserGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserGetUserGroupOK creates a ResonateUserGetUserGroupOK with default headers values
func NewResonateUserGetUserGroupOK() *ResonateUserGetUserGroupOK {
	return &ResonateUserGetUserGroupOK{}
}

/* ResonateUserGetUserGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserGetUserGroupOK struct {
	Payload *models.UserUserGroupPublicResponse
}

func (o *ResonateUserGetUserGroupOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/usergroup/{id}][%d] resonateUserGetUserGroupOK  %+v", 200, o.Payload)
}
func (o *ResonateUserGetUserGroupOK) GetPayload() *models.UserUserGroupPublicResponse {
	return o.Payload
}

func (o *ResonateUserGetUserGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserUserGroupPublicResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserGetUserGroupDefault creates a ResonateUserGetUserGroupDefault with default headers values
func NewResonateUserGetUserGroupDefault(code int) *ResonateUserGetUserGroupDefault {
	return &ResonateUserGetUserGroupDefault{
		_statusCode: code,
	}
}

/* ResonateUserGetUserGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserGetUserGroupDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user get user group default response
func (o *ResonateUserGetUserGroupDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserGetUserGroupDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/usergroup/{id}][%d] ResonateUser_GetUserGroup default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserGetUserGroupDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserGetUserGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
