// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// NewResonateUserAddUserGroupParams creates a new ResonateUserAddUserGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserAddUserGroupParams() *ResonateUserAddUserGroupParams {
	return &ResonateUserAddUserGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserAddUserGroupParamsWithTimeout creates a new ResonateUserAddUserGroupParams object
// with the ability to set a timeout on a request.
func NewResonateUserAddUserGroupParamsWithTimeout(timeout time.Duration) *ResonateUserAddUserGroupParams {
	return &ResonateUserAddUserGroupParams{
		timeout: timeout,
	}
}

// NewResonateUserAddUserGroupParamsWithContext creates a new ResonateUserAddUserGroupParams object
// with the ability to set a context for a request.
func NewResonateUserAddUserGroupParamsWithContext(ctx context.Context) *ResonateUserAddUserGroupParams {
	return &ResonateUserAddUserGroupParams{
		Context: ctx,
	}
}

// NewResonateUserAddUserGroupParamsWithHTTPClient creates a new ResonateUserAddUserGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserAddUserGroupParamsWithHTTPClient(client *http.Client) *ResonateUserAddUserGroupParams {
	return &ResonateUserAddUserGroupParams{
		HTTPClient: client,
	}
}

/* ResonateUserAddUserGroupParams contains all the parameters to send to the API endpoint
   for the resonate user add user group operation.

   Typically these are written to a http.Request.
*/
type ResonateUserAddUserGroupParams struct {

	// Body.
	Body *models.UserUserGroupCreateRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user add user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserAddUserGroupParams) WithDefaults() *ResonateUserAddUserGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user add user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserAddUserGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) WithTimeout(timeout time.Duration) *ResonateUserAddUserGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) WithContext(ctx context.Context) *ResonateUserAddUserGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) WithHTTPClient(client *http.Client) *ResonateUserAddUserGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) WithBody(body *models.UserUserGroupCreateRequest) *ResonateUserAddUserGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) SetBody(body *models.UserUserGroupCreateRequest) {
	o.Body = body
}

// WithID adds the id to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) WithID(id string) *ResonateUserAddUserGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user add user group params
func (o *ResonateUserAddUserGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserAddUserGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
