// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResonateUserListUsersUserGroupsParams creates a new ResonateUserListUsersUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserListUsersUserGroupsParams() *ResonateUserListUsersUserGroupsParams {
	return &ResonateUserListUsersUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserListUsersUserGroupsParamsWithTimeout creates a new ResonateUserListUsersUserGroupsParams object
// with the ability to set a timeout on a request.
func NewResonateUserListUsersUserGroupsParamsWithTimeout(timeout time.Duration) *ResonateUserListUsersUserGroupsParams {
	return &ResonateUserListUsersUserGroupsParams{
		timeout: timeout,
	}
}

// NewResonateUserListUsersUserGroupsParamsWithContext creates a new ResonateUserListUsersUserGroupsParams object
// with the ability to set a context for a request.
func NewResonateUserListUsersUserGroupsParamsWithContext(ctx context.Context) *ResonateUserListUsersUserGroupsParams {
	return &ResonateUserListUsersUserGroupsParams{
		Context: ctx,
	}
}

// NewResonateUserListUsersUserGroupsParamsWithHTTPClient creates a new ResonateUserListUsersUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserListUsersUserGroupsParamsWithHTTPClient(client *http.Client) *ResonateUserListUsersUserGroupsParams {
	return &ResonateUserListUsersUserGroupsParams{
		HTTPClient: client,
	}
}

/* ResonateUserListUsersUserGroupsParams contains all the parameters to send to the API endpoint
   for the resonate user list users user groups operation.

   Typically these are written to a http.Request.
*/
type ResonateUserListUsersUserGroupsParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user list users user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserListUsersUserGroupsParams) WithDefaults() *ResonateUserListUsersUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user list users user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserListUsersUserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) WithTimeout(timeout time.Duration) *ResonateUserListUsersUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) WithContext(ctx context.Context) *ResonateUserListUsersUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) WithHTTPClient(client *http.Client) *ResonateUserListUsersUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) WithID(id string) *ResonateUserListUsersUserGroupsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user list users user groups params
func (o *ResonateUserListUsersUserGroupsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserListUsersUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
