// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResonateUserDeleteUserGroupParams creates a new ResonateUserDeleteUserGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserDeleteUserGroupParams() *ResonateUserDeleteUserGroupParams {
	return &ResonateUserDeleteUserGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserDeleteUserGroupParamsWithTimeout creates a new ResonateUserDeleteUserGroupParams object
// with the ability to set a timeout on a request.
func NewResonateUserDeleteUserGroupParamsWithTimeout(timeout time.Duration) *ResonateUserDeleteUserGroupParams {
	return &ResonateUserDeleteUserGroupParams{
		timeout: timeout,
	}
}

// NewResonateUserDeleteUserGroupParamsWithContext creates a new ResonateUserDeleteUserGroupParams object
// with the ability to set a context for a request.
func NewResonateUserDeleteUserGroupParamsWithContext(ctx context.Context) *ResonateUserDeleteUserGroupParams {
	return &ResonateUserDeleteUserGroupParams{
		Context: ctx,
	}
}

// NewResonateUserDeleteUserGroupParamsWithHTTPClient creates a new ResonateUserDeleteUserGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserDeleteUserGroupParamsWithHTTPClient(client *http.Client) *ResonateUserDeleteUserGroupParams {
	return &ResonateUserDeleteUserGroupParams{
		HTTPClient: client,
	}
}

/* ResonateUserDeleteUserGroupParams contains all the parameters to send to the API endpoint
   for the resonate user delete user group operation.

   Typically these are written to a http.Request.
*/
type ResonateUserDeleteUserGroupParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user delete user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserDeleteUserGroupParams) WithDefaults() *ResonateUserDeleteUserGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user delete user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserDeleteUserGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) WithTimeout(timeout time.Duration) *ResonateUserDeleteUserGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) WithContext(ctx context.Context) *ResonateUserDeleteUserGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) WithHTTPClient(client *http.Client) *ResonateUserDeleteUserGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) WithID(id string) *ResonateUserDeleteUserGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user delete user group params
func (o *ResonateUserDeleteUserGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserDeleteUserGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
