// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserUpdateUserGroupReader is a Reader for the ResonateUserUpdateUserGroup structure.
type ResonateUserUpdateUserGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserUpdateUserGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserUpdateUserGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserUpdateUserGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserUpdateUserGroupOK creates a ResonateUserUpdateUserGroupOK with default headers values
func NewResonateUserUpdateUserGroupOK() *ResonateUserUpdateUserGroupOK {
	return &ResonateUserUpdateUserGroupOK{}
}

/* ResonateUserUpdateUserGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserUpdateUserGroupOK struct {
	Payload models.UserEmpty
}

func (o *ResonateUserUpdateUserGroupOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/usergroup/{id}][%d] resonateUserUpdateUserGroupOK  %+v", 200, o.Payload)
}
func (o *ResonateUserUpdateUserGroupOK) GetPayload() models.UserEmpty {
	return o.Payload
}

func (o *ResonateUserUpdateUserGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserUpdateUserGroupDefault creates a ResonateUserUpdateUserGroupDefault with default headers values
func NewResonateUserUpdateUserGroupDefault(code int) *ResonateUserUpdateUserGroupDefault {
	return &ResonateUserUpdateUserGroupDefault{
		_statusCode: code,
	}
}

/* ResonateUserUpdateUserGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserUpdateUserGroupDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user update user group default response
func (o *ResonateUserUpdateUserGroupDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserUpdateUserGroupDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/usergroup/{id}][%d] ResonateUser_UpdateUserGroup default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserUpdateUserGroupDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserUpdateUserGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
