// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// ResonateUserAddUserGroupReader is a Reader for the ResonateUserAddUserGroup structure.
type ResonateUserAddUserGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResonateUserAddUserGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResonateUserAddUserGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewResonateUserAddUserGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewResonateUserAddUserGroupOK creates a ResonateUserAddUserGroupOK with default headers values
func NewResonateUserAddUserGroupOK() *ResonateUserAddUserGroupOK {
	return &ResonateUserAddUserGroupOK{}
}

/* ResonateUserAddUserGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type ResonateUserAddUserGroupOK struct {
	Payload *models.UserUserRequest
}

func (o *ResonateUserAddUserGroupOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/users/{id}/usergroup][%d] resonateUserAddUserGroupOK  %+v", 200, o.Payload)
}
func (o *ResonateUserAddUserGroupOK) GetPayload() *models.UserUserRequest {
	return o.Payload
}

func (o *ResonateUserAddUserGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserUserRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResonateUserAddUserGroupDefault creates a ResonateUserAddUserGroupDefault with default headers values
func NewResonateUserAddUserGroupDefault(code int) *ResonateUserAddUserGroupDefault {
	return &ResonateUserAddUserGroupDefault{
		_statusCode: code,
	}
}

/* ResonateUserAddUserGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ResonateUserAddUserGroupDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the resonate user add user group default response
func (o *ResonateUserAddUserGroupDefault) Code() int {
	return o._statusCode
}

func (o *ResonateUserAddUserGroupDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/users/{id}/usergroup][%d] ResonateUser_AddUserGroup default  %+v", o._statusCode, o.Payload)
}
func (o *ResonateUserAddUserGroupDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ResonateUserAddUserGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
