// Code generated by go-swagger; DO NOT EDIT.

package usergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/resonatecoop/user-api/client/models"
)

// NewResonateUserUpdateUserGroupParams creates a new ResonateUserUpdateUserGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserUpdateUserGroupParams() *ResonateUserUpdateUserGroupParams {
	return &ResonateUserUpdateUserGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserUpdateUserGroupParamsWithTimeout creates a new ResonateUserUpdateUserGroupParams object
// with the ability to set a timeout on a request.
func NewResonateUserUpdateUserGroupParamsWithTimeout(timeout time.Duration) *ResonateUserUpdateUserGroupParams {
	return &ResonateUserUpdateUserGroupParams{
		timeout: timeout,
	}
}

// NewResonateUserUpdateUserGroupParamsWithContext creates a new ResonateUserUpdateUserGroupParams object
// with the ability to set a context for a request.
func NewResonateUserUpdateUserGroupParamsWithContext(ctx context.Context) *ResonateUserUpdateUserGroupParams {
	return &ResonateUserUpdateUserGroupParams{
		Context: ctx,
	}
}

// NewResonateUserUpdateUserGroupParamsWithHTTPClient creates a new ResonateUserUpdateUserGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserUpdateUserGroupParamsWithHTTPClient(client *http.Client) *ResonateUserUpdateUserGroupParams {
	return &ResonateUserUpdateUserGroupParams{
		HTTPClient: client,
	}
}

/* ResonateUserUpdateUserGroupParams contains all the parameters to send to the API endpoint
   for the resonate user update user group operation.

   Typically these are written to a http.Request.
*/
type ResonateUserUpdateUserGroupParams struct {

	// Body.
	Body *models.UserUserGroupUpdateRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user update user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserUpdateUserGroupParams) WithDefaults() *ResonateUserUpdateUserGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user update user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserUpdateUserGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) WithTimeout(timeout time.Duration) *ResonateUserUpdateUserGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) WithContext(ctx context.Context) *ResonateUserUpdateUserGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) WithHTTPClient(client *http.Client) *ResonateUserUpdateUserGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) WithBody(body *models.UserUserGroupUpdateRequest) *ResonateUserUpdateUserGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) SetBody(body *models.UserUserGroupUpdateRequest) {
	o.Body = body
}

// WithID adds the id to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) WithID(id string) *ResonateUserUpdateUserGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user update user group params
func (o *ResonateUserUpdateUserGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserUpdateUserGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
