// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserMembershipResponse user user membership response
//
// swagger:model userUserMembershipResponse
type UserUserMembershipResponse struct {

	// end
	End string `json:"end,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// membership class
	MembershipClass string `json:"membershipClass,omitempty"`

	// start
	Start string `json:"start,omitempty"`
}

// Validate validates this user user membership response
func (m *UserUserMembershipResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user membership response based on context it is used
func (m *UserUserMembershipResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserMembershipResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserMembershipResponse) UnmarshalBinary(b []byte) error {
	var res UserUserMembershipResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
