// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserUpdateRequest user user update request
//
// swagger:model userUserUpdateRequest
type UserUserUpdateRequest struct {

	// country
	Country string `json:"country,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// full name
	FullName string `json:"fullName,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// newsletter notification
	NewsletterNotification bool `json:"newsletterNotification,omitempty"`

	// role Id
	RoleID int32 `json:"roleId,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user user update request
func (m *UserUserUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user update request based on context it is used
func (m *UserUserUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserUpdateRequest) UnmarshalBinary(b []byte) error {
	var res UserUserUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
