// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserGroupPrivateResponse user user group private response
//
// swagger:model userUserGroupPrivateResponse
type UserUserGroupPrivateResponse struct {

	// avatar
	Avatar string `json:"avatar,omitempty"`

	// banner
	Banner string `json:"banner,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// repeated string followers = 9;
	// repeated string members = 10;
	// repeated string memberOfGroups = 11;
	// repeated string links = 12;
	// repeated string tags = 13;
	//  StreetAddress address = 13;
	// Privacy privacy = 14;
	// repeated RelatedUserGroup recommended_artists = 15;
	// map<string, string> publisher = 16;
	// map<string, string> pro = 17;
	GroupEmail string `json:"groupEmail,omitempty"`

	// group type
	GroupType string `json:"groupType,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// owner Id
	OwnerID string `json:"ownerId,omitempty"`

	// short bio
	ShortBio string `json:"shortBio,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// Validate validates this user user group private response
func (m *UserUserGroupPrivateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user group private response based on context it is used
func (m *UserUserGroupPrivateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserGroupPrivateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserGroupPrivateResponse) UnmarshalBinary(b []byte) error {
	var res UserUserGroupPrivateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
