// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserGroupUpdateRequest user user group update request
//
// swagger:model userUserGroupUpdateRequest
type UserUserGroupUpdateRequest struct {

	// avatar
	Avatar string `json:"avatar,omitempty"`

	// banner
	Banner string `json:"banner,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// group email
	GroupEmail string `json:"groupEmail,omitempty"`

	// group type
	GroupType string `json:"groupType,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// links
	Links []string `json:"links"`

	// owner Id
	OwnerID string `json:"ownerId,omitempty"`

	// short bio
	ShortBio string `json:"shortBio,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this user user group update request
func (m *UserUserGroupUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user group update request based on context it is used
func (m *UserUserGroupUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserGroupUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserGroupUpdateRequest) UnmarshalBinary(b []byte) error {
	var res UserUserGroupUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
