// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserRequest user user request
//
// swagger:model userUserRequest
type UserUserRequest struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this user user request
func (m *UserUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user request based on context it is used
func (m *UserUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserRequest) UnmarshalBinary(b []byte) error {
	var res UserUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
