// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserPrivateResponse user user private response
//
// swagger:model userUserPrivateResponse
type UserUserPrivateResponse struct {

	// country
	Country string `json:"country,omitempty"`

	// email confirmed
	EmailConfirmed bool `json:"emailConfirmed,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// followed groups
	FollowedGroups []string `json:"followedGroups"`

	// full name
	FullName string `json:"fullName,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// legacy Id
	LegacyID int32 `json:"legacyId,omitempty"`

	// member
	Member bool `json:"member,omitempty"`

	// newsletter notification
	NewsletterNotification bool `json:"newsletterNotification,omitempty"`

	// owned groups
	OwnedGroups []string `json:"ownedGroups"`

	// personas
	Personas []string `json:"personas"`

	// role Id
	RoleID int32 `json:"roleId,omitempty"`

	// tenant Id
	TenantID int32 `json:"tenantId,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user user private response
func (m *UserUserPrivateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user private response based on context it is used
func (m *UserUserPrivateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserPrivateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserPrivateResponse) UnmarshalBinary(b []byte) error {
	var res UserUserPrivateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
