// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserUpdateRestrictedRequest user user update restricted request
//
// swagger:model userUserUpdateRestrictedRequest
type UserUserUpdateRestrictedRequest struct {

	// first name
	FirstName string `json:"firstName,omitempty"`

	// full name
	FullName string `json:"fullName,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// member
	Member bool `json:"member,omitempty"`

	// newsletter notification
	NewsletterNotification bool `json:"newsletterNotification,omitempty"`

	// role Id
	RoleID int32 `json:"roleId,omitempty"`

	// tenant Id
	TenantID int32 `json:"tenantId,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user user update restricted request
func (m *UserUserUpdateRestrictedRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user update restricted request based on context it is used
func (m *UserUserUpdateRestrictedRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserUpdateRestrictedRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserUpdateRestrictedRequest) UnmarshalBinary(b []byte) error {
	var res UserUserUpdateRestrictedRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
