// Code generated by go-swagger; DO NOT EDIT.

package membership

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResonateUserGetUserMembershipParams creates a new ResonateUserGetUserMembershipParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResonateUserGetUserMembershipParams() *ResonateUserGetUserMembershipParams {
	return &ResonateUserGetUserMembershipParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResonateUserGetUserMembershipParamsWithTimeout creates a new ResonateUserGetUserMembershipParams object
// with the ability to set a timeout on a request.
func NewResonateUserGetUserMembershipParamsWithTimeout(timeout time.Duration) *ResonateUserGetUserMembershipParams {
	return &ResonateUserGetUserMembershipParams{
		timeout: timeout,
	}
}

// NewResonateUserGetUserMembershipParamsWithContext creates a new ResonateUserGetUserMembershipParams object
// with the ability to set a context for a request.
func NewResonateUserGetUserMembershipParamsWithContext(ctx context.Context) *ResonateUserGetUserMembershipParams {
	return &ResonateUserGetUserMembershipParams{
		Context: ctx,
	}
}

// NewResonateUserGetUserMembershipParamsWithHTTPClient creates a new ResonateUserGetUserMembershipParams object
// with the ability to set a custom HTTPClient for a request.
func NewResonateUserGetUserMembershipParamsWithHTTPClient(client *http.Client) *ResonateUserGetUserMembershipParams {
	return &ResonateUserGetUserMembershipParams{
		HTTPClient: client,
	}
}

/* ResonateUserGetUserMembershipParams contains all the parameters to send to the API endpoint
   for the resonate user get user membership operation.

   Typically these are written to a http.Request.
*/
type ResonateUserGetUserMembershipParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resonate user get user membership params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserGetUserMembershipParams) WithDefaults() *ResonateUserGetUserMembershipParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resonate user get user membership params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResonateUserGetUserMembershipParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) WithTimeout(timeout time.Duration) *ResonateUserGetUserMembershipParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) WithContext(ctx context.Context) *ResonateUserGetUserMembershipParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) WithHTTPClient(client *http.Client) *ResonateUserGetUserMembershipParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) WithID(id string) *ResonateUserGetUserMembershipParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resonate user get user membership params
func (o *ResonateUserGetUserMembershipParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResonateUserGetUserMembershipParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
