// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/common.proto

package user

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Empty) Validate() error {
	return nil
}
func (this *RelatedUserGroup) Validate() error {
	return nil
}
func (this *User) Validate() error {
	return nil
}
func (this *Tag) Validate() error {
	return nil
}
func (this *StreetAddress) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Query) Validate() error {
	return nil
}
func (this *SearchResults) Validate() error {
	for _, item := range this.People {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("People", err)
			}
		}
	}
	for _, item := range this.Artists {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Artists", err)
			}
		}
	}
	for _, item := range this.Labels {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Labels", err)
			}
		}
	}
	return nil
}
