// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StreetAdressServiceClient is the client API for StreetAdressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreetAdressServiceClient interface {
	SearchStreetAddress(ctx context.Context, in *Query, opts ...grpc.CallOption) (*StreetAddress, error)
}

type streetAdressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreetAdressServiceClient(cc grpc.ClientConnInterface) StreetAdressServiceClient {
	return &streetAdressServiceClient{cc}
}

func (c *streetAdressServiceClient) SearchStreetAddress(ctx context.Context, in *Query, opts ...grpc.CallOption) (*StreetAddress, error) {
	out := new(StreetAddress)
	err := c.cc.Invoke(ctx, "/user.StreetAdressService/SearchStreetAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreetAdressServiceServer is the server API for StreetAdressService service.
// All implementations should embed UnimplementedStreetAdressServiceServer
// for forward compatibility
type StreetAdressServiceServer interface {
	SearchStreetAddress(context.Context, *Query) (*StreetAddress, error)
}

// UnimplementedStreetAdressServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStreetAdressServiceServer struct {
}

func (UnimplementedStreetAdressServiceServer) SearchStreetAddress(context.Context, *Query) (*StreetAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchStreetAddress not implemented")
}

// UnsafeStreetAdressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreetAdressServiceServer will
// result in compilation errors.
type UnsafeStreetAdressServiceServer interface {
	mustEmbedUnimplementedStreetAdressServiceServer()
}

func RegisterStreetAdressServiceServer(s grpc.ServiceRegistrar, srv StreetAdressServiceServer) {
	s.RegisterService(&_StreetAdressService_serviceDesc, srv)
}

func _StreetAdressService_SearchStreetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetAdressServiceServer).SearchStreetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.StreetAdressService/SearchStreetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetAdressServiceServer).SearchStreetAddress(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreetAdressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.StreetAdressService",
	HandlerType: (*StreetAdressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchStreetAddress",
			Handler:    _StreetAdressService_SearchStreetAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/streetaddress.proto",
}
