// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/upload_submissions_messages.proto

//package example;
//package resonate.api.user;

package user

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UploadSubmissionRequest) Validate() error {
	return nil
}
func (this *UploadSubmissionAddRequest) Validate() error {
	return nil
}
func (this *UploadSubmissionUpdateRequest) Validate() error {
	return nil
}
