// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.17.3
// source: user/upload_submissions_messages.proto

//package example;
//package resonate.api.user;

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadSubmissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UploadSubmissionRequest) Reset() {
	*x = UploadSubmissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_upload_submissions_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSubmissionRequest) ProtoMessage() {}

func (x *UploadSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_upload_submissions_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSubmissionRequest.ProtoReflect.Descriptor instead.
func (*UploadSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_user_upload_submissions_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UploadSubmissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UploadSubmissionAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // UUID required
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // required
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // required
	Files       []string `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *UploadSubmissionAddRequest) Reset() {
	*x = UploadSubmissionAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_upload_submissions_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadSubmissionAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSubmissionAddRequest) ProtoMessage() {}

func (x *UploadSubmissionAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_upload_submissions_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSubmissionAddRequest.ProtoReflect.Descriptor instead.
func (*UploadSubmissionAddRequest) Descriptor() ([]byte, []int) {
	return file_user_upload_submissions_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSubmissionAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadSubmissionAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadSubmissionAddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadSubmissionAddRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type UploadSubmissionUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // UUID required
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // required
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // required
	Files       []string `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *UploadSubmissionUpdateRequest) Reset() {
	*x = UploadSubmissionUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_upload_submissions_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadSubmissionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSubmissionUpdateRequest) ProtoMessage() {}

func (x *UploadSubmissionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_upload_submissions_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSubmissionUpdateRequest.ProtoReflect.Descriptor instead.
func (*UploadSubmissionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_upload_submissions_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSubmissionUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadSubmissionUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadSubmissionUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadSubmissionUpdateRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_user_upload_submissions_messages_proto protoreflect.FileDescriptor

var file_user_upload_submissions_messages_proto_rawDesc = []byte{
	0x0a, 0x26, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x75,
	0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x29,
	0x0a, 0x17, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x78, 0x0a, 0x1a, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x7b, 0x0a, 0x1d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x6e, 0x61, 0x74, 0x65, 0x63, 0x6f, 0x6f, 0x70, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_upload_submissions_messages_proto_rawDescOnce sync.Once
	file_user_upload_submissions_messages_proto_rawDescData = file_user_upload_submissions_messages_proto_rawDesc
)

func file_user_upload_submissions_messages_proto_rawDescGZIP() []byte {
	file_user_upload_submissions_messages_proto_rawDescOnce.Do(func() {
		file_user_upload_submissions_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_upload_submissions_messages_proto_rawDescData)
	})
	return file_user_upload_submissions_messages_proto_rawDescData
}

var file_user_upload_submissions_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_upload_submissions_messages_proto_goTypes = []interface{}{
	(*UploadSubmissionRequest)(nil),       // 0: user.UploadSubmissionRequest
	(*UploadSubmissionAddRequest)(nil),    // 1: user.UploadSubmissionAddRequest
	(*UploadSubmissionUpdateRequest)(nil), // 2: user.UploadSubmissionUpdateRequest
}
var file_user_upload_submissions_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_upload_submissions_messages_proto_init() }
func file_user_upload_submissions_messages_proto_init() {
	if File_user_upload_submissions_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_upload_submissions_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadSubmissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_upload_submissions_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadSubmissionAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_upload_submissions_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadSubmissionUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_upload_submissions_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_upload_submissions_messages_proto_goTypes,
		DependencyIndexes: file_user_upload_submissions_messages_proto_depIdxs,
		MessageInfos:      file_user_upload_submissions_messages_proto_msgTypes,
	}.Build()
	File_user_upload_submissions_messages_proto = out.File
	file_user_upload_submissions_messages_proto_rawDesc = nil
	file_user_upload_submissions_messages_proto_goTypes = nil
	file_user_upload_submissions_messages_proto_depIdxs = nil
}
